spring:
  profiles:
    active:
    - dev
#spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/hting-demo?characterEncoding=utf8&useSSL=false
#    username: root
#    password: 
#    
#    druid:
#      initial-size: 1
#      max-active: 20
#      min-idle: 1
#      
#      max-wait: 60000
#      pool-prepared-statements: true
#      max-pool-prepared-statement-per-connection-size: 20
#      validation-query: select 1 from dual
#      test-on-borrow: false
#      test-on-return: false
#      test-while-idle: true
#      time-between-eviction-runs-millis: 60000
#      min-evictable-idle-time-millis: 3000000
#      filters: stat,wall
#    
#    
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#      naming:
#        strategy: 
#    